name: Build Demos
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [rework]
    paths-ignore: ["**/*.md"]
  schedule:
    - cron: "0 7 1/14 * *"
  workflow_dispatch: {}

jobs:
  build:
    name: "${{ matrix.script }} (${{ matrix.arch }})"
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runs-on: ubuntu-latest
            script: vkcube-glxgears-appimage
          - arch: aarch64
            runs-on: ubuntu-latest-arm
            script: vkcube-glxgears-appimage
          - arch: x86_64
            runs-on: ubuntu-latest
            script: zink-vkcube-glxgears-appimage
          - arch: aarch64
            runs-on: ubuntu-latest-arm
            script: zink-vkcube-glxgears-appimage
          - arch: x86_64
            runs-on: ubuntu-latest
            script: gtk3-demo-appimage
          - arch: aarch64
            runs-on: ubuntu-latest-arm
            script: gtk3-demo-appimage
          - arch: x86_64
            runs-on: ubuntu-latest
            script: gtk4-demo-appimage
          - arch: aarch64
            runs-on: ubuntu-latest-arm
            script: gtk4-demo-appimage
          - arch: x86_64
            runs-on: ubuntu-latest
            script: gtk4-demo-onlysoftware-appimage
          - arch: aarch64
            runs-on: ubuntu-latest-arm
            script: gtk4-demo-onlysoftware-appimage
          - arch: x86_64
            runs-on: ubuntu-latest
            script: qt6-dbus-demo-appimage
          - arch: aarch64
            runs-on: ubuntu-latest-arm
            script: qt6-dbus-demo-appimage
          - arch: x86_64
            runs-on: ubuntu-latest
            script: qt6-dbus-demo-onlysoftware-appimage
          - arch: aarch64
            runs-on: ubuntu-latest-arm
            script: qt6-dbus-demo-onlysoftware-appimage
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - uses: actions/checkout@v6

      - name: Make AppImage
        run: sh ./src/demo/${{ matrix.script }}.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: AppImage-${{ matrix.arch }}-${{ matrix.script }}
          path: dist

  release:
    if: ${{ github.ref_name == 'main' && needs.build.result == 'success' }}
    needs: [build]
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: AppImage-*
          merge-multiple: true

      - name: Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
          name: "demos"
          tag_name: "demo"
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            *.AppImage
